version: '3'

services:
  mysql:
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-store:/var/lib/mysql
  redis:
    image: redis
    volumes:
      - redis-store:/data
  rails:
    build: .
    command: /bin/sh -c "rm -rf /app/tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_HOST: mysql
      SELENIUM_URL: http://selenium-server:4444/wd/hub
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - .:/app
      - assets-store:/app/public/assets
      - bundler-store:/app/vendor/bundle
      - node-modules-store:/app/node_modules
  webpack:
    image: docker_rails_sample_rails:latest
    command: bin/webpack-dev-server
    # ports:
      # - '3035:3035'
    tty: true
    volumes:
      - .:/app
      - assets-store:/app/public/assets
      - bundler-store:/app/vendor/bundle
      - node-modules-store:/app/node_modules
  selenium-server:
    image: selenium/standalone-chrome-debug:3.11.0-bismuth
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm

volumes:
  mysql-store:
  redis-store:
  bundler-store:
  node-modules-store:
  assets-store:
