version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - postgres-store:/var/lib/postgresql
  redis:
    image: redis
    volumes:
      - redis-store:/data
  rails:
    build: .
    command: /bin/sh -c "rm -rf /app/tmp/pids/server.pid && bundle exec foreman start"
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
      - assets-store:/app/public/assets
      - assets-cache-store:/app/tmp/cache/assets

volumes:
  assets-cache-store:
  assets-store:
  postgres-store:
    driver: local
  redis-store:
