version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - postgres-store:/var/lib/postgresql
  redis:
    image: redis
    volumes:
      - redis-store:/data
  rails:
    build: .
    command: /bin/sh -c "rm -rf /app/tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./db:/app/db
      - ./log:/app/log
      - ./public:/app/public
      - ./test:/app/test
      - ./tmp:/app/tmp
      - ~/.ssh:/root/.ssh
  webpack:
    build: .
    command: bin/webpack-dev-server
    # ports:
      # - '3035:3035'
    tty: true
    volumes:
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config

volumes:
  postgres-store:
    driver: local
  redis-store:
