version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip \
              bash
            pip install \
              docker-compose==1.21.0
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 3
      - run:
          name: docker-compose run rails bin/setup
          command: docker-compose run --rm rails bin/setup
      - run:
          name: test
          command: docker-compose run --rm rails bin/rails test test/*
      - run:
          name: docker-compose down
          command: docker-compose down
