version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    environment:
      RAILS_ENV: test
      NODE_ENV: test
    steps:
      - checkout
      - run:
          name: update docker-compose
          command: pip install docker-compose==1.22.0
      - run:
          name: check docker-compose version
          command: docker-compose --version
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 10
      - run:
          name: docker-compose exec rails bin/setup
          command: docker-compose exec rails bin/setup
      - run:
          name: test
          command: docker-compose exec rails bin/rails test test/*
      - run:
          name: docker-compose down
          command: docker-compose down
workflows:
  version: 2
  build:
    jobs:
      - build
